# Generated by Django 4.1 on 2022-09-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_funcionario_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
                ('icone', models.CharField(choices=[('lni-layers', 'Camadas'), ('lni-cog', 'Engrenagem'), ('lni-rocket', 'Foguete'), ('lni-leaf', 'Folha'), ('lni-laptop-phone', 'Laptop'), ('lni-mobile', 'Mobile'), ('lni-users', 'Usuários')], max_length=25, verbose_name='Ícone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='bio',
            field=models.TextField(max_length=200, verbose_name='Biooooo'),
        ),
    ]
