# Generated by Django 4.1 on 2022-09-13 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_funcionario_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurso',
            options={'verbose_name': 'Recurso', 'verbose_name_plural': 'Recursos'},
        ),
    ]
