# Generated by Django 4.1 on 2022-09-14 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_nameprice_suporte_alter_preco_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de Suporte')),
            ],
            options={
                'verbose_name': 'Tipo de Atualização',
                'verbose_name_plural': 'Tipos de Atualizações',
            },
        ),
        migrations.AlterField(
            model_name='preco',
            name='atualizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.atualizacao', verbose_name='Atualização'),
        ),
    ]
